name: 'aws-authenticate'
description: ''
inputs:
  vault_addr:
    description: ''
    required: true
  aws_region:
    description: ''
    required: false
    default: us-east-1
runs:
  using: 'composite'
  steps:
    - name: Install Vault
      uses: innovationnorway/setup-vault@v1
    - name: Generate AWS credentials
      shell: bash
      run: |
        vault read -address=${{ inputs.vault_addr }} aws/sts/${NODIS_VAULT_ROLE} --format=json > creds.json
        AWS_ACCESS_KEY_ID="$(jq -r '.data.access_key' creds.json)"
        AWS_SECRET_ACCESS_KEY="$(jq -r '.data.secret_key' creds.json)"
        AWS_SESSION_TOKEN="$(jq -r '.data.security_token' creds.json)"
        AWS_ROLE_ARN="$(vault kv get -address=${{ inputs.vault_addr }} --format=json secret/aws/role/${NODIS_VAULT_ROLE} | jq -r '.data.data.arn')"
        echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
        echo "::add-mask::${AWS_ACCESS_KEY_ID}"
        echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV
        echo "::add-mask::${AWS_SECRET_ACCESS_KEY}"
        echo "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" >> $GITHUB_ENV
        echo "::add-mask::${AWS_SESSION_TOKEN}"
        echo "AWS_ROLE_ARN=${AWS_ROLE_ARN}" >> $GITHUB_ENV
        echo "::add-mask::${AWS_ROLE_ARN}"
        echo "AWS_REGION=${{ inputs.aws_region }}" >> $GITHUB_ENV
        