name: 'aws-authenticate'
description: ''
inputs:
  vault_addr:
    description: ''
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Vault
      uses: innovationnorway/setup-vault@v1
    - name: Generate AWS credentials
      shell: bash
      run: |
        set -e
        export AWS_ROLE_ARN=$(vault kv get -address=${{ inputs.vault_addr }}} --format=json secret/aws/role/${NODIS_VAULT_ROLE | jq -r '.arn')
        vault read -address=${{ inputs.vault_addr }} aws/sts/${NODIS_VAULT_ROLE} --format=json > creds.json
        export AWS_ACCESS_KEY_ID=$(jq -r '.data.access_key' creds.json)
        export AWS_SECRET_ACCESS_KEY=$(jq -r '.data.secret_key' creds.json)
        export AWS_SESSION_TOKEN=$(jq -r '.data.security_token' creds.json)
        